version: '3'
services:
  cai:
    build: .
    ports:
      - "5002:5000"
    environment:
      - SECRET_KEY=supersecret
      - ENTREE_USER=entree
      - ENTREE_PASS=entreepass
      - SORTIE_USER=sortie
      - SORTIE_PASS=sortiepass
      - WEBHOOK_URL=https://cai.apc38.app
    volumes:
      - .:/app
    restart: unless-stopped
